### ISSUE TITLE
Unable to make it work with an SLZB-06M

### ISSUE THREAD

**Issue by ajavibp** [ownbee/hass-otbr-docker#4]
I have tried it with the SLZB-06M and have not been able to get it to work. The container starts, but I am unable to link my device (an Aqara U200).

**Comment by donnib** [comment]
Can you share your docker-compose, i am trying the same thing but unable to get it to work, here is mine :

```
services:
  otbr:
    container_name: otbr
    image: ghcr.io/ownbee/hass-otbr-docker
    restart: unless-stopped
    privileged: true # don't change this !
    network_mode: host # don't change this !
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      BACKBONE_IF: ens18
      FLOW_CONTROL: 0
      FIREWALL: 0
      NAT64: 1
      BAUDRATE: 460800
      OTBR_REST_PORT: 8081
      OTBR_WEB_PORT: 7586
      AUTOFLASH_FIRMWARE: 0
      network_device: 10.10.0.150:6638
    devices:
      - /dev/net/tun:/dev/net/tun
    #volumes:
    #  - /var/docker_data/otbr:/var/lib/thread/

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/docker_data/matter:/data/
      - /run/dbus:/run/dbus:ro  # For bluetooth
      - /etc/localtime:/etc/localtime:ro
    command: >
      --storage-path /data
      --paa-root-cert-dir /data/credentials
      --bluetooth-adapter 0
      --log-level-sdk progress
      --primary-interface ens18
```
I just get following error :
```
otbr           | s6-rc: info: service mdns: starting
otbr           | s6-rc: info: service s6rc-oneshot-runner: starting
otbr           | s6-rc: info: service mdns successfully started
otbr           | s6-rc: info: service s6rc-oneshot-runner successfully started
otbr           | s6-rc: info: service fix-attrs: starting
otbr           | s6-rc: info: service banner: starting
otbr           | INFO: Starting mDNS Responder...
otbr           | s6-rc: info: service banner successfully started
otbr           | s6-rc: info: service universal-silabs-flasher: starting
otbr           | Default: mDNSResponder (Engineering Build) (Jan 14 2025 21:04:03) starting
otbr           | INFO: Flashing firmware is disabled
otbr           | s6-rc: info: service universal-silabs-flasher successfully started
otbr           | s6-rc: info: service fix-attrs successfully started
otbr           | s6-rc: info: service legacy-cont-init: starting
otbr           | s6-rc: info: service legacy-cont-init successfully started
otbr           | s6-rc: info: service otbr-agent: starting
otbr           | INFO: Starting otbr-agent...
otbr           | [NOTE]-AGENT---: Running 0.3.0-b067e5ac-dirty
otbr           | [NOTE]-AGENT---: Thread version: 1.3.0
otbr           | [NOTE]-AGENT---: Thread interface: wpan0
otbr           | [NOTE]-AGENT---: Radio URL: spinel+hdlc+uart://?uart-baudrate=460800&uart-init-deassert
otbr           | [NOTE]-AGENT---: Radio URL: trel://ens18
otbr           | [NOTE]-ILS-----: Infra link selected: ens18
otbr           | [INFO]-RCP_HOS-: OpenThread log level changed to 4
otbr           | 63d.09:19:54.834 [C] Platform------: Init() at hdlc_interface.cpp:153: No such file or directory
otbr           | WARNING: otbr-agent exited with code 5 (by signal 0).
```

**Comment by ownbee** [comment]
Only advice i can give is to make sure ipv6 works on your lan and your host computer. That was one of my problems. My router had it disabled by default.

**Comment by donnib** [comment]
Thx, i am sure the ipv6 network works as it should, i think the problem is somewhere else now. It seems it's not connecting to the network device (it's different than your case where you use a USB device).

**Comment by ownbee** [comment]
I think otbr advice against network devices since the communication is latency sensitive. However, I cannot help you, I have no network device to test with. I may have accidentally wiped out configuration for it in this container since I did not thought about that use-case. Feel free to compare this repo with hass original config. But since hass original only support hassos basically, it may not be supported fully there either.

**Comment by ajavibp** [comment]
> Can you share your docker-compose, i am trying the same thing but unable to get it to work, here is mine :

I use the device from USB. I can't get the service up over the network.

```
services:
  otbr:
    container_name: otbr
    image: ghcr.io/ownbee/hass-otbr-docker
    restart: unless-stopped
    privileged: true # don't change this !
    network_mode: host # don't change this !
    dns: 127.0.0.1
    stdin_open: true
    tty: true
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
      - IPC_LOCK
    environment:
      DEVICE: /dev/ttyUSB1
      #NETWORK_DEVICE: 192.168.22.30:6638
      BAUDRATE: 460800
      FLOW_CONTROL: 0
      NAT64: 1
      OTBR_REST_PORT: 8081
      OTBR_WEB_PORT: 8085
      OTBR_REST_LISTEN_PORT: 8081
      AUTOFLASH_FIRMWARE: 0
      BACKBONE_IF: enp1s0
#      TUN_INTERFACE_NAME: enp1s0
      OTBR_ENABLE: 1
      FIREWALL: 0
      OTBR_LOG_LEVEL: debug
      TZ: Europe/Madrid
      RADIO_URL: "spinel+hdlc+uart:///dev/ttyUSB1"
    devices:
      - /dev/serial/by-id/usb-SMLIGHT_SMLIGHT_SLZB-06M_52db2bc05b73ed11aa5d75773dbf42d5-if00-port0:/dev/ttyUSB1
    volumes:
      - /home/javi/docker/matter-thread/openthread:/var/lib/thread:rw
      - /etc/localtime:/etc/localtime:ro
      
  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    network_mode: host
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - /home/javi/docker/matter-thread/matter:/data
#      - /run/dbus:/run/dbus:ro  # For bluetooth
      - /etc/localtime:/etc/localtime:ro
    command: >
      --storage-path /data
      --paa-root-cert-dir /data/credentials
      --log-level-sdk info
 #     --primary-interface enp1s0     
 #     --bluetooth-adapter 0
    environment:
      - TZ=Europe/Madrid
```
