### ISSUE TITLE
Container in Kubernetes

### ISSUE THREAD

**Issue by xlemassacre** [ownbee/hass-otbr-docker#5]
Thank you for providing this container. I'm trying to set up this container in my Kubernetes cluster (single node microk8s), but I'm struggling to get it fully up and running.

My setup:
In the cluster, there is already Home Assistant running with other containers like zwave-js-ui and zigbee2mqtt. Also ghcr.io/home-assistant-libs/python-matter-server is already working with ipv4 and v6 enabled.

Now I am trying to add thread to my setup. I've tried using the openthread/otbr image and also your image. But I always get stuck at the same point when commissioning from the Home Assistant companion app, which seems to be a connection test from the Androind Phone to the Thread device.

To rule out other errors (USB stick, ...), I also set up a temporary Hassos system with the OTBR addon. But I used my existing Home Assistant and Matter setup and connected it to this OTBR from Hassos. This worked perfectly and I was able to successfully commission the device. So my conclusion at the moment is that there is a problem with the otbr container on my cluster.

Configuration:
```
spec:
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: "[{ \n  \"name\": \"otbr-conf\",\n  \"namespace\":
          \"smarthome\",\n  \"ips\": [\"192.168.1.37/24\"]\n}]\n"
    spec:
      containers:
      - env:
        - name: AUTOFLASH_FIRMWARE
          value: "0"
        - name: BACKBONE_IF
          value: net1
        - name: BAUDRATE
          value: "460800"
        - name: DEBUG
          value: "true"
        - name: DEVICE
          value: /tmp/ttyOTBR
        - name: FIREWALL
          value: "0"
        - name: FLOW_CONTROL
          value: "1"
        - name: NAT64
          value: "0"
        - name: NETWORK_DEVICE
          value: 192.168.1.11:20104
        - name: OTBR_ENABLE
          value: "1"
        - name: OTBR_INFRA_IF
          value: net1
        - name: OTBR_LOG_LEVEL
          value: debug
        - name: OTBR_REST_LISTEN_PORT
          value: "8081"
        - name: OTBR_REST_PORT
          value: "8081"
        - name: OTBR_WEB_PORT
          value: "8080"
        - name: TZ
          value: Europe/Berlin
        image: ghcr.io/ownbee/hass-otbr-docker:v0.1.1
        imagePullPolicy: IfNotPresent
        name: main
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/thread
          name: data
      dnsPolicy: ClusterFirst

      initContainers:
      - args:
        - -c
        - sysctl -w net.ipv6.conf.net1.accept_ra_rt_info_max_plen=128 && sysctl -w
          net.ipv6.conf.net1.accept_ra=2 && sysctl -w net.ipv6.conf.net1.disable_ipv6=0
          && sysctl -w net.ipv4.conf.net1.forwarding=1 && sysctl -w net.ipv6.conf.net1.forwarding=1
        command:
        - /bin/sh
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        name: sysctler
        securityContext:
          privileged: true
```

The net1 interface is connected to the container via multus. When I start commissioning, I see traffic (via tcpdump) reaching the vm where kubernetes is running. This traffic is also forwarded to the net1 interface in the otbr, which then also creates an IPv6 address for the device.
The thread device can be pinged inside the otbr container using that created ip.When I ping the device outside the container, it reaches the net1 interface in the container, but then it does not seem to be forwarded to wpan0.
I've tried so many things now to find out exactly what the problem is, but I can't get this last step to work.

I'm not sure if this is the right place to ask this question, but reading the readme in the repo, it sounds like you've also had some trouble getting this to work, and maybe you have some hints on what I could check.

**Comment by xlemassacre** [comment]
Got it working now, changed the init container to:
```
initContainers:
      sysctler:
        image:
          repository: busybox
          tag: latest
          pullPolicy: IfNotPresent

        securityContext:
          privileged: true
        command: ["/bin/sh"]
        args:
          - -c
          - sysctl -w net.ipv6.conf.net1.accept_ra_rt_info_max_plen=128 &&
            sysctl -w net.ipv6.conf.net1.accept_ra=2 &&
            sysctl -w net.ipv6.conf.net1.disable_ipv6=0 &&
            sysctl -w net.ipv4.conf.net1.forwarding=1 &&
            sysctl -w net.ipv6.conf.all.forwarding=1
```

And also changed the multus configuration to type macvlan:

```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "macvlan",
    "mode": "bridge",
    "master": "ens19",
    "ipam": {
      "type": "host-local",

```
